package com.demo.common.model;

import com.demo.common.model.base.BaseStudent;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Student extends BaseStudent<Student> {
	
	public static final Student me = new Student();
	
	/**
	 * 所有 sql 与业务逻辑写在 Model 或 Service 中，不要写在 Controller 中，养成好习惯，有利于大型项目的开发与维护
	 */
	public Page<Student> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from student order by id asc");
	}
	
	public Page<Student> paginate(int pageNumber, int pageSize, String name) {
		return paginate(pageNumber, pageSize, "select *", "from student where name = '"+name+"'order by id asc");
	}
	
}
